name: Build and Deploy

on: [ push ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Run Gradle build
        run: ./gradlew clean test shadowJar jpi -PbuildVersion="${{ github.sha }}" --stacktrace

      - name: Build and push Docker image
        if: github.ref_name == 'main' || github.ref_name == 'develop'
        run: |
          chmod +x ./scripts/*.sh
          case ${{ github.ref_name }} in
              main)
                  ./scripts/docker-build.sh -l latest
                  ;;
              develop)
                  ./scripts/docker-build.sh -l beta
                  ;;
              *)
                  echo "No release required for branch: ${{ github.ref_name }}"
                  ;;
          esac
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag release
        if: github.ref_name == 'main'
        run: ./scripts/release-trigger.sh
